### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [MarkRabey/wharf#2]
Hi, , I want to design a new logo for the project completely free...

**Comment by MarkRabey** [comment]
That would be great. Feel free! You're welcome to either create the files sizes and update the project, or if you prefer, you can send me the files I can will update the actual code. Whatever you prefer. I'm not at all wedded to any colours or anything.

**Comment by Arslanshn** [comment]
https://drive.google.com/drive/folders/1JlUvG9nbnwaTm8ZFotldkgBzvfusIqv9?usp=sharing

**Comment by Arslanshn** [comment]
If you like the Hello logo, please respond
;-)

**Comment by MarkRabey** [comment]
To be honest, I don't really like it. Thanks though.

**Comment by Arslanshn** [comment]
I can do it if you tell me what kind of logo you want. To be honest, I understand what the project is doing.
